# SPDX-FileCopyrightText: 2025 MiromindAI
#
# SPDX-License-Identifier: Apache-2.0

"""Background task execution for agent runs."""

import asyncio
import json
import logging
import os
import re
import threading
import traceback
import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from typing import Any

from ..core.config import AppConfig
from ..core.session_manager import SessionManager
from ..models.task import FileInfo

logger = logging.getLogger(__name__)
# from miroflow.logging.task_tracer import get_tracer

# logger = get_tracer()

# Placeholder / invalid-answer strings that mean "no real answer was produced".
# SummaryGenerator emits the skip-placeholder when the task hit the turn limit
# mid-run; FinalAnswerExtractor emits the other strings when LLM extraction
# failed; extract_gaia_final_answer emits "NO_ANSWER" / "CANNOT_DETERMINE" etc.
# when the summary contains no useful information.
# Keep in sync with eval_utils.INVALID_ANSWER_MARKERS and
# fallback_final_answer_generator._PLACEHOLDER_ANSWERS.
_NO_ANSWER_PLACEHOLDERS = frozenset(
    {
        "No final answer generated.",
        "Final response is generated by LLM, but no \\boxed{} content found.",
        "Task interrupted due to context limit.",
        "Task incomplete - skipping answer generation to retry with failure experience.",
        # Returned by extract_gaia_final_answer / eval_utils.INVALID_ANSWER_MARKERS
        "NO_ANSWER",
        "INSUFFICIENT_INFO",
        "CANNOT_DETERMINE",
        "None",
        "none",
        "N/A",
        "n/a",
        "NONE",
        "Unknown",
        "unknown",
        "UNKNOWN",
    }
)
_MAX_EVENT_RESULT_LENGTH = 3000
_TRUNCATION_SUFFIX = "\n... (truncated)"


def _is_placeholder(s: str) -> bool:
    """Return True if *s* is empty or a known "no answer" placeholder string."""
    return not s or s in _NO_ANSWER_PLACEHOLDERS

class TaskExecutor:
    """Executes agent tasks in background threads."""

    def __init__(self, config: AppConfig, session_manager: SessionManager):
        self.config = config
        self.session_manager = session_manager
        self.executor = ThreadPoolExecutor(max_workers=config.max_concurrent_tasks)
        self._running_tasks: dict[str, threading.Thread] = {}
        self._task_tracers: dict[str, Any] = {}
        #z
        self._task_loops: dict[str, asyncio.AbstractEventLoop] = {}
        self._async_tasks: dict[str, asyncio.Task] = {}
        # Agent pool — injected by dependencies after warmup (may be None)
        self.agent_pool: Any | None = None

    def submit_task(
        self,
        task_id: str,
        task_description: str,
        config_path: str,
        file_info: FileInfo | None = None,
    ) -> None:
        """Submit a task for background execution."""
        loop: asyncio.AbstractEventLoop | None = None
        # loop = asyncio.new_event_loop()
        # self._task_loops[task_id] = loop
        
        # thread = threading.Thread(
        #     target=self._run_task_sync,
        #     # args=(task_id, task_description, config_path, file_info),
        #     args=(task_id, task_description, config_path, file_info, loop),
        #     daemon=True,
        # )
        # self._running_tasks[task_id] = thread
        # thread.start()
        try:
            loop = asyncio.new_event_loop()
            self._task_loops[task_id] = loop
            thread = threading.Thread(
                target=self._run_task_sync,
                # args=(task_id, task_description, config_path, file_info),
                args=(task_id, task_description, config_path, file_info, loop),
                daemon=True,
            )
            self._running_tasks[task_id] = thread
            thread.start()
        except Exception:
            self._task_loops.pop(task_id, None)
            self._running_tasks.pop(task_id, None)
            if loop is not None:
                loop.close()
            raise

    def _run_task_sync(
        self,
        task_id: str,
        task_description: str,
        config_path: str,
        file_info: FileInfo | None,
        loop: asyncio.AbstractEventLoop,
    ) -> None:
        """Synchronous wrapper for async task execution."""
        # asyncio.run(self._run_task(task_id, task_description, config_path, file_info))
        # if loop is None:
        #     loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(
                self._run_task_wrapper(task_id, task_description, config_path, file_info)
            )
        finally:
            # Drain any remaining pending tasks before closing the loop
            # pending = asyncio.all_tasks(loop)
            pending = [t for t in asyncio.all_tasks(loop) if not t.done()]
            if pending:
                loop.run_until_complete(asyncio.gather(*pending, return_exceptions=True))
            loop.close()
            self._task_loops.pop(task_id, None)
            
    async def _run_task_wrapper(
        self,
        task_id: str,
        task_description: str,
        config_path: str,
        file_info: FileInfo | None,
    ) -> None:
        """Wrapper that stores the asyncio.Task reference for external cancellation."""
        current = asyncio.current_task()
        if current is not None:
            self._async_tasks[task_id] = current
        try:
            await self._run_task(task_id, task_description, config_path, file_info)
        except asyncio.CancelledError:
            self.session_manager.update_task(
                task_id,
                {
                    "status": "cancelled",
                    "error_message": "Task cancelled by user",
                },
            )
            raise
        finally:
            self._async_tasks.pop(task_id, None)

    async def _run_task(
        self,
        task_id: str,
        task_description: str,
        config_path: str,
        file_info: FileInfo | None,
    ) -> None:
        """Execute agent task asynchronously."""
        # Change to project root for relative imports
        os.chdir(self.config.project_root)

        tracer = None
        agent = None
        agent_is_overflow = False
        should_release_to_pool = False  # tracks whether to return agent to pool

        try:
            # Import MiroFlow components (import here to avoid circular imports)
            from config import load_config
            # from miroflow.agents import build_agent_from_config
            from miroflow.agents.context import AgentContext
            from miroflow.logging.task_tracer import get_tracer, set_tracer

            # Update status to running
            self.session_manager.update_task(task_id, {"status": "running"})

            # Create unique output directory
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            #z 之前已有的生成方法：task_id = f"task_{uuid.uuid4().hex[:12]}"
            run_id = task_id.split('_')[1] #z 不用这个 str(uuid.uuid4())[:8]，用之前的就可以了
            output_dir = self.config.logs_dir / f"{timestamp}_{run_id}" #z logs/web_runs
            output_dir.mkdir(parents=True, exist_ok=True)

            # Load configuration
            logger.info(f'z:config_path = {config_path}')
            cfg = load_config(config_path, f"output_dir={output_dir}")

            # Get max_turns from config
            max_turns = 30
            if hasattr(cfg, "main_agent") and hasattr(cfg.main_agent, "max_turns"):
                max_turns = cfg.main_agent.max_turns

            # Update session with log path and max_turns
            self.session_manager.update_task(
                task_id,
                {
                    "log_path": str(output_dir),
                    "max_turns": max_turns,
                },
            )

            # Setup tracer
            set_tracer(cfg.output_dir)
            tracer = get_tracer()
            tracer.set_log_path(cfg.output_dir)
            self._task_tracers[task_id] = tracer

            # Build agent
            logger.info(f'#z 使用agent池')
            # agent = build_agent_from_config(cfg=cfg)
            # Acquire agent — use pool when available and config matches,
            # otherwise fall back to building a new (overflow) agent.
            pool = self.agent_pool
            pool_config = self.config.default_config
            use_pool = (
                pool is not None
                and config_path == pool_config
                and self.config.agent_pool_strategy == "overflow_create"
            )

            if use_pool:
                try:
                    agent, agent_is_overflow = pool.acquire()
                    should_release_to_pool = True
                    logger.debug(
                        "task %s: acquired agent from pool (overflow=%s, available=%d)",
                        task_id,
                        agent_is_overflow,
                        pool.available,
                    )
                except RuntimeError:
                    # max_overflow reached — build a temporary agent anyway
                    logger.warning(
                        "task %s: pool max_overflow reached, building temporary agent",
                        task_id,
                    )
                    agent = build_agent_from_config(cfg=cfg)
                    agent_is_overflow = True
                    should_release_to_pool = False
            else:
                # No pool, non-default config, or non-overflow strategy
                agent = build_agent_from_config(cfg=cfg)
                agent_is_overflow = True  # treat as overflow so it's not returned
                should_release_to_pool = False
            
            logger.info(f'#z 使用agent池完成')
            # Build context
            ctx_kwargs: dict[str, Any] = {"task_description": task_description}

            if file_info:
                # Pass the absolute file path as task_file_name (string)
                # This is what InputMessageGenerator expects
                ctx_kwargs["task_file_name"] = file_info.absolute_file_path

            ctx = AgentContext(**ctx_kwargs)

            # Start tracer
            tracer.start()
            tracer.update_task_meta(
                {
                    "task_id": task_id,
                    "task_description": task_description,
                }
            )

            # Run agent
            logger.info(f'#z agent.run 运行中')
            result = await agent.run(ctx)
            logger.info(f'#z agent.run 运行完成')

            # # Get final message history before cleanup
            # final_messages = self._get_all_messages_from_tracer(tracer)
            # Get final message history and trajectory before cleanup
            final_data = self._get_all_messages_from_tracer(tracer)

            # Update session with results and full message history
            raw_final_answer = result.get("final_boxed_answer", "") or ""
            raw_summary = result.get("summary", "") or ""
            raw_llm_extracted = result.get("llm_extracted_final_answer", "") or ""
            exceed_max_turn_summary = result.get("exceed_max_turn_summary", "") or ""

            logger.info(
                f'''[task:{task_id}] raw results —
                final_boxed_answer={raw_final_answer[:120] if raw_final_answer else ""}
                | summary={raw_summary[:120] if raw_summary else ""} | 
                llm_extracted_final_answer={raw_llm_extracted[:120] if raw_llm_extracted else ""} |
                 exceed_max_turn_summary={exceed_max_turn_summary[:120] if exceed_max_turn_summary else ""}
                '''
            )
            final_answer = raw_final_answer
            summary = raw_summary

            # Safety net: surface exceed_max_turn_summary whenever final_answer or
            # summary is absent / a known placeholder so the user always sees
            # something meaningful in the web UI.
            if _is_placeholder(final_answer) and exceed_max_turn_summary:
                logger.info(
                    f"[task:{task_id}] final_answer is placeholder {final_answer} — replacing with exceed_max_turn_summary"
                )
                final_answer = exceed_max_turn_summary
            if _is_placeholder(summary):
                logger.info(
                        f"[task:{task_id}] summary is placeholder {summary} — replacing with exceed_max_turn_summary"
                    )
                if exceed_max_turn_summary:
                    summary = exceed_max_turn_summary
                elif final_answer:
                    logger.info(
                        f"[task:{task_id}] summary is placeholder — copying from final_answer"
                    )
                    summary = final_answer
            logger.info(
                f"[task:{task_id}] final results — final_answer={final_answer[:120] if final_answer else ''} | summary={summary[:120] if summary else ''}"
            )

            self.session_manager.update_task(
                task_id,
                {
                    "status": "completed",
                    "final_answer": final_answer,
                    "summary": summary,
                    # "messages": final_messages,
                    "messages": final_data["messages"], #z
                    "trajectory": final_data["trajectory"],
                },
            )

            tracer.finish(status="completed")

        except Exception as e:
            error_msg = f"{e!s}\n{traceback.format_exc()}"
            error_data = self._get_all_messages_from_tracer(tracer) if tracer else {
                "messages": [],
                "trajectory": [],
            }
            self.session_manager.update_task(
                task_id,
                {
                    "status": "failed",
                    "error_message": error_msg,
                    "messages": error_data.get("messages", []),
                    "trajectory": error_data.get("trajectory", [])
                    + [
                        {
                            "id": f"err_{uuid.uuid4().hex[:8]}",
                            "type": "tool_call",
                            "tool_name": "agent_execution",
                            "status": "error",
                            "error": str(e),
                        }
                    ],
                },
            )
            if tracer:
                tracer.finish(status="failed", error=str(e))

        finally:
            # Release agent back to the pool (or discard overflow agent)
            if agent is not None and should_release_to_pool and pool is not None:
                pool.release(agent, agent_is_overflow)
                logger.info(
                    f"task {task_id}: released agent (overflow={agent_is_overflow}, pool_available={pool.available})"
                )

            # Cleanup task tracking
            if task_id in self._running_tasks:
                del self._running_tasks[task_id]
            if task_id in self._task_tracers:
                del self._task_tracers[task_id]

    # def _get_all_messages_from_tracer(self, tracer: Any) -> list[dict]:
    #     """Extract all messages from tracer for persistence."""
    def _get_all_messages_from_tracer(self, tracer: Any) -> dict[str, Any]: #z
        """Extract all messages and trajectory from tracer for persistence."""
        try:
            with tracer._data_lock:
                for key, log_file in tracer._active_tasks.items():
                    agent_states = log_file.agent_states
                    for agent_name, state in agent_states.items():
                        state_data = (
                            state.state
                            if hasattr(state, "state")
                            else state.get("state", {})
                        )
                        message_history = state_data.get("message_history", [])
                        # return self._format_messages(message_history)
                        return {
                            "messages": self._format_messages(message_history),
                            "trajectory": self._build_trajectory(message_history),
                        }
        except Exception:
            logger.debug("Failed to retrieve task messages", exc_info=True)
        return {"messages": [], "trajectory": []}
        # return []

    def get_task_progress(self, task_id: str) -> dict[str, Any]:#z 前端api
        """Get current progress from tracer."""
        tracer = self._task_tracers.get(task_id)
        if tracer is None:
            return {
                "current_turn": 0,
                "step_count": 0,
                "recent_logs": [],
                "messages": [],
                "trajectory": [],
            }

        try:
            with tracer._data_lock:
                for key, log_file in tracer._active_tasks.items():
                    agent_states = log_file.agent_states
                    step_logs = log_file.step_logs

                    # Calculate turn count and get message history
                    current_turn = 0
                    messages = []
                    message_history = []
                    #z 只取了最后一个agent数据：单 agent 场景（绝大多数情况）——只有一个main_agent：循环只走一次，没问题。
                    #z for的是字典
                    for agent_name, state in agent_states.items():
                        state_data = (
                            state.state
                            if hasattr(state, "state")
                            else state.get("state", {})
                        )
                        message_history = state_data.get("message_history", [])
                        current_turn = max(
                            current_turn, (len(message_history) + 1) // 2
                        )
                        # 运行中仅展示清洗后的助手进展消息
                        messages = self._format_messages_filter(message_history)
                        #z 多agent应该这样吧
                        # message_history.extend(hist)          # 合并所有 agent 的消息
                        # messages.extend(self._format_messages(hist))

                    # Filter and format logs to show tool calls
                    recent_logs = (
                        self._format_recent_logs(step_logs[-30:]) if step_logs else []
                    )
                    # Build structured trajectory from message history #z
                    trajectory = self._build_trajectory(message_history)

                    return {
                        "current_turn": current_turn,
                        "step_count": log_file.get_valid_step_count(),#len(step_logs), #z
                        "recent_logs": recent_logs,
                        "messages": messages,
                        "trajectory": trajectory,
                    }
        except Exception:
            logger.warning("Failed to retrieve task progress", exc_info=True)

        # return {"current_turn": 0, "step_count": 0, "recent_logs": [], "messages": []}
        return {"current_turn": 0, "step_count": 0, "recent_logs": [], "messages": [], "trajectory": []}

    def _format_recent_logs(self, logs: list[dict]) -> list[dict]:
        """Format and filter logs to show relevant tool call and LLM information."""
        formatted = []
        for log in logs:
            log_type = log.get("type", "")

            # Include tool calls and results
            if (
                "tool" in log_type.lower()
                or log.get("tool_name")
                or log.get("server_name")
            ):
                formatted.append(
                    {
                        "type": "tool_call",
                        "tool_name": log.get("tool_name", ""),
                        "server_name": log.get("server_name", ""),
                        "input": self._truncate_output(
                            log.get("input") or log.get("arguments") or log.get("args")
                        ),
                        "output": self._truncate_output(
                            log.get("output") or log.get("result") or log.get("content")
                        ),
                    }
                )
            # Include LLM calls
            elif "llm" in log_type.lower() or log.get("model") or log.get("prompt"):
                formatted.append(
                    {
                        "type": "llm_call",
                        "model": log.get("model", ""),
                        "input": self._truncate_output(
                            log.get("prompt") or log.get("input") or log.get("messages")
                        ),
                        "output": self._truncate_output(
                            log.get("response")
                            or log.get("output")
                            or log.get("content")
                        ),
                    }
                )
            # Include span events (shows execution flow)
            elif log_type in ("span_start", "span_end"):
                path = log.get("path", "")
                # Only include interesting spans
                if any(
                    x in path.lower()
                    for x in ["tool", "search", "read", "llm", "agent", "mcp"]
                ):
                    formatted.append(
                        {
                            "type": log_type,
                            "path": path,
                            "name": path.split("/")[-1] if path else "",
                        }
                    )
            # Include any log with tool-related or LLM-related fields
            elif any(
                key in log
                for key in ["tool_name", "server_name", "tool_call", "model", "prompt"]
            ):
                formatted.append(log)

        # Return last 15 formatted logs
        return formatted[-15:]

    def _format_messages(self, messages: list[dict]) -> list[dict]:
        """Format message history for display.

        Note: We do NOT truncate message content here to preserve:
        - Full thinking/reasoning content for proper display
        - Complete tool results (e.g., search results JSON) for parsing
        """
        formatted = []
        for msg in messages:
            role = msg.get("role", "unknown")
            content = msg.get("content", "")

            # Handle different content types
            if isinstance(content, list):
                # Tool results or multi-part content
                text_parts = []
                for item in content:
                    if isinstance(item, dict):
                        if item.get("type") == "text":
                            text_parts.append(item.get("text", ""))
                        elif item.get("type") == "tool_result":
                            # Don't truncate tool results - need full JSON for parsing
                            tool_content = item.get("content", "")
                            if isinstance(tool_content, str):
                                text_parts.append(tool_content)
                            else:
                                text_parts.append(str(tool_content))
                        elif item.get("type") == "tool_use":
                            text_parts.append(f"[Tool Call: {item.get('name', '')}]")
                    elif isinstance(item, str):
                        text_parts.append(item)
                content = "\n".join(text_parts)
            elif not isinstance(content, str):
                content = str(content)

            # Don't truncate - preserve full content for thinking and tool results
            formatted_msg: dict = {
                "role": role,
                "content": content,
            }
            #z
            # For assistant messages, also include dedicated reasoning as <think> block
            # so the frontend fallback (parseMessageContent) can render it.
            if role == "assistant":
                dedicated = msg.get("reasoning") or msg.get("reasoning_content")
                if dedicated and isinstance(dedicated, str) and dedicated.strip():
                    formatted_msg["content"] = (
                        f"<think>{dedicated.strip()}</think>\n{content}"
                    )

            formatted.append(formatted_msg)

        return formatted
    
    def _format_messages_filter(self, messages: list[dict]) -> list[dict]:
        """Format message history for display.

        Minimal, safe approach:
        - 过滤 role == 'system'
        - 过滤包含 FILTER_PATTERNS 的消息内容
        - 保持原始结构（role + content），并附带 optional metadata if present
        """
        
        def _is_system_message(msg: dict) -> bool:
            role = msg.get("role", "").lower()
            # 运行中界面已单独展示用户问题，不再重复显示 user/system 原始提示
            if role in {"system", "user"}:
                return True

            content = msg.get("content", "")
            # 将内容视为字符串来检测噪声模式（list/dict 会被 str() 化）
            try:
                content_str = content if isinstance(content, str) else str(content)
            except Exception:
                content_str = ""

            # 可扩展的噪声/系统提示模式（短且明确）
            FILTER_PATTERNS = [
                "Tool-Use Formatting Instructions",
                "<server_name>server name here</server_name>",
                "<tool_name>tool name here</tool_name>",
                # "Tool-Use Formatting",
                # "You only have access to the tools",
                # "In this environment you have access",
                # "Server name:",
                # "Tool name:",
                # "<use_mcp_tool>",
                # "General Objective",
                # "Task Strategy",
                # "Tool-Use Communication Rules",
                # "Skills (via MCP server",
                # "Today is:",  # 日志里注入日期的系统行
                "Your task is to comprehensively address the question by actively collecting detailed information from the web",
                # "In this environment you have access to a set of tools you can use to answer the user's question"
            ]

            lower = content_str.lower()
            for p in FILTER_PATTERNS:
                if p.lower() in lower:
                    return True

            return False
        
        formatted = []
        for msg in messages:
            # 1) 过滤系统/噪声消息
            if _is_system_message(msg):
                # print(f'in: _format_messages_filter:过滤掉了系统提示~')
                continue
        
            role = msg.get("role", "unknown")
            content = msg.get("content", "")

            # Handle different content types
            if isinstance(content, list):
                # Tool results or multi-part content
                text_parts = []
                for item in content:
                    if isinstance(item, dict):
                        if item.get("type") == "text":
                            text_parts.append(item.get("text", ""))
                        elif item.get("type") == "tool_result":
                            # Don't truncate tool results - need full JSON for parsing
                            tool_content = item.get("content", "")
                            if isinstance(tool_content, str):
                                text_parts.append(tool_content)
                            else:
                                text_parts.append(str(tool_content))
                        elif item.get("type") == "tool_use":
                            text_parts.append(f"[Tool Call: {item.get('name', '')}]")
                    elif isinstance(item, str):
                        text_parts.append(item)
                content = "\n".join(text_parts)
            elif not isinstance(content, str):
                content = str(content)

            # Don't truncate - preserve full content for thinking and tool results
            formatted_msg: dict = {
                "role": role,
                "content": content,
            }
            if role == "assistant":
                dedicated = msg.get("reasoning") or msg.get("reasoning_content")
                if dedicated and isinstance(dedicated, str) and dedicated.strip():
                    formatted_msg["content"] = (
                        f"<think>{dedicated.strip()}</think>\n{content}"
                    )
            formatted.append(formatted_msg)
        # if formatted:
        #     print(f'in: _format_messages_filter:\n{formatted}')
        return formatted

    def _truncate_output(self, output: Any) -> Any:
        """Truncate long output strings."""
        if output is None:
            return None
        if isinstance(output, str) and len(output) > 1000:
            return output[:1000] + "... (truncated)"
        return output

    def cancel_task(self, task_id: str) -> bool:
        """Cancel a running task (best effort - marks as cancelled)."""
        loop = self._task_loops.get(task_id)
        task = self._async_tasks.get(task_id)
        if loop and task and not task.done():
            # Schedule cancellation inside the task's event loop (thread-safe)
            logger.info(f'#z if loop and task and not task.done()')
            loop.call_soon_threadsafe(task.cancel)
            return True

        if len(self._running_tasks) == 0:# 历史任务直接停
            self.session_manager.update_task(
                task_id,
                {
                    "status": "cancelled",
                    "error_message": "Task cancelled by user",
                },
            )
            return True
        
        if task_id in self._running_tasks:
            self.session_manager.update_task(
                task_id,
                {
                    "status": "cancelled",
                    "error_message": "Task cancelled by user",
                },
            )
            return True
        return False

    def is_task_running(self, task_id: str) -> bool:
        """Check if a task is currently running."""
        return task_id in self._running_tasks
    
    #z 
    # ------------------------------------------------------------------
    # Trajectory building
    # ------------------------------------------------------------------

    def _build_trajectory(self, message_history: list[dict]) -> list[dict]:
        """Build a structured trajectory from the raw message_history.

        Supports both:
        - Native OpenAI tool_calls (role=assistant with tool_calls list, role=tool)
        - MCP XML format (<use_mcp_tool>...</use_mcp_tool> / <tool_result>)
        """
        events: list[dict] = []
        counter = [0]

        def new_id(prefix: str = "evt") -> str:
            counter[0] += 1
            return f"{prefix}_{counter[0]}"

        # Pending tool calls awaiting results
        native_pending: dict[str, dict] = {}  # call_id -> event
        mcp_pending: list[dict] = []  # ordered, matches user messages in sequence

        # Context for assigning parent_id to reasoning events
        last_completed_type: str | None = None  # "search" | "read"
        last_search_id: str | None = None
        last_read_id: str | None = None

        for msg in message_history:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if role == "assistant":
                # Determine reasoning parent from last completed tool
                if last_completed_type == "search":
                    reasoning_parent = last_search_id
                elif last_completed_type == "read":
                    reasoning_parent = last_read_id
                else:
                    reasoning_parent = None

                # Extract <think> block from content string
                think_extracted = False
                if isinstance(content, str):
                    think_match = re.search(
                        r"<think>([\s\S]*?)</think>", content, re.IGNORECASE
                    )
                    if think_match:
                        reasoning_text = think_match.group(1).strip()
                        if reasoning_text:
                            evt_id = new_id("r")
                            events.append(
                                {
                                    "id": evt_id,
                                    "type": "reasoning",
                                    "text": reasoning_text,
                                    "parent_id": reasoning_parent,
                                }
                            )
                            think_extracted = True

                # Also check dedicated reasoning field (e.g., Kimi/DeepSeek via OpenRouter)
                # saved by process_llm_response as assistant_message["reasoning"]
                if not think_extracted:
                    dedicated_reasoning = msg.get("reasoning") or msg.get(
                        "reasoning_content"
                    )
                    if (
                        dedicated_reasoning
                        and isinstance(dedicated_reasoning, str)
                        and dedicated_reasoning.strip()
                    ):
                        evt_id = new_id("r")
                        events.append(
                            {
                                "id": evt_id,
                                "type": "reasoning",
                                "text": dedicated_reasoning.strip(),
                                "parent_id": reasoning_parent,
                            }
                        )

                # Handle native OpenAI tool_calls
                native_tool_calls = msg.get("tool_calls", [])
                if native_tool_calls and isinstance(native_tool_calls, list):
                    for tc in native_tool_calls:
                        if not isinstance(tc, dict):
                            continue
                        call_id = tc.get("id", new_id("call"))
                        fn = tc.get("function", {})
                        tool_name = fn.get("name", "") if isinstance(fn, dict) else str(fn)
                        args_str = fn.get("arguments", "{}") if isinstance(fn, dict) else "{}"
                        try:
                            args = json.loads(args_str) if isinstance(args_str, str) else {}
                        except Exception:
                            args = {"raw": str(args_str)[:500]}

                        evt_id = new_id("t")
                        evt = self._make_tool_event(evt_id, tool_name, args, last_search_id)
                        events.append(evt)
                        native_pending[call_id] = evt
                        if evt["type"] == "search":
                            last_search_id = evt_id

                # Handle MCP XML tool calls
                if isinstance(content, str) and "<use_mcp_tool" in content:
                    mcp_pattern = re.compile(
                        r"<use_mcp_tool[^>]*>.*?"
                        r"(?:<server_name[^>]*>(.*?)</server_name>.*?)?"
                        r"<tool_name[^>]*>(.*?)</tool_name>.*?"
                        r"<arguments[^>]*>([\s\S]*?)</arguments>.*?"
                        r"</use_mcp_tool>",
                        re.IGNORECASE | re.DOTALL,
                    )
                    for match in mcp_pattern.finditer(content):
                        tool_name = (match.group(2) or "").strip()
                        args_str = (match.group(3) or "").strip()
                        try:
                            args = json.loads(args_str) if args_str else {}
                        except Exception:
                            args = {"raw": args_str[:500]}

                        evt_id = new_id("t")
                        evt = self._make_tool_event(evt_id, tool_name, args, last_search_id)
                        events.append(evt)
                        mcp_pending.append(evt)
                        if evt["type"] == "search":
                            last_search_id = evt_id

            elif role == "tool":
                # Native tool result message
                call_id = msg.get("tool_call_id", "")
                raw_content = content
                if isinstance(raw_content, list):
                    parts = []
                    for item in raw_content:
                        if isinstance(item, dict):
                            parts.append(
                                item.get("text") or item.get("content") or ""
                            )
                        else:
                            parts.append(str(item))
                    raw_content = "\n".join(parts)
                elif not isinstance(raw_content, str):
                    raw_content = str(raw_content)

                matched_evt = native_pending.get(call_id)
                if matched_evt:
                    self._apply_result_to_event(matched_evt, raw_content)
                    if matched_evt["type"] == "search":
                        last_completed_type = "search"
                        last_search_id = matched_evt["id"]
                    elif matched_evt["type"] == "read":
                        last_completed_type = "read"
                        last_read_id = matched_evt["id"]

            elif role == "user":
                # Collect text from user message (tool results in MCP / text protocol)
                texts: list[str] = []
                if isinstance(content, str):
                    texts.append(content)
                elif isinstance(content, list):
                    for item in content:
                        if isinstance(item, dict):
                            t = item.get("text") or item.get("content") or ""
                            if t:
                                texts.append(str(t))
                        elif isinstance(item, str):
                            texts.append(item)

                full_text = "\n".join(texts)
                if not full_text:
                    continue

                # Try to match <tool_result>name:\ncontent</tool_result> blocks
                tool_result_re = re.compile(
                    r"<tool_result>\s*(\S[^:\n]*?):\s*([\s\S]*?)</tool_result>",
                    re.IGNORECASE,
                )
                tool_result_matches = list(tool_result_re.finditer(full_text))

                if tool_result_matches:
                    for rm in tool_result_matches:
                        tool_name_in_result = rm.group(1).strip()
                        result_text = rm.group(2).strip()

                        # Match to first unresolved MCP pending call with same tool_name
                        matched = None
                        for evt in mcp_pending:
                            if (
                                evt.get("tool_name") == tool_name_in_result
                                and not evt.get("_resolved")
                            ):
                                matched = evt
                                break
                        if not matched:
                            # Fallback: any first unresolved
                            for evt in mcp_pending:
                                if not evt.get("_resolved"):
                                    matched = evt
                                    break

                        if matched:
                            matched["_resolved"] = True
                            self._apply_result_to_event(matched, result_text)
                            if matched["type"] == "search":
                                last_completed_type = "search"
                                last_search_id = matched["id"]
                            elif matched["type"] == "read":
                                last_completed_type = "read"
                                last_read_id = matched["id"]

                elif mcp_pending:
                    # text_protocol: whole content is the tool result for the first pending call
                    for evt in mcp_pending:
                        if not evt.get("_resolved"):
                            evt["_resolved"] = True
                            self._apply_result_to_event(evt, full_text)
                            if evt["type"] == "search":
                                last_completed_type = "search"
                                last_search_id = evt["id"]
                            elif evt["type"] == "read":
                                last_completed_type = "read"
                                last_read_id = evt["id"]
                            break

        # Remove internal tracking keys before returning
        for evt in events:
            evt.pop("_resolved", None)

        return events

    def _make_tool_event(
        self,
        evt_id: str,
        tool_name: str,
        args: dict,
        last_search_id: str | None,
    ) -> dict:
        """Create a trajectory event dict for a tool call."""
        tool_lower = tool_name.lower()

        if any(
            x in tool_lower
            for x in ("search", "google", "serper", "bing", "ddg", "tavily", "serpapi")
        ):
            query = str(
                args.get("query")
                or args.get("q")
                or args.get("search_query")
                or args.get("keyword")
                or ""
            )
            return {
                "id": evt_id,
                "type": "search",
                "query": query,
                "results": [],
                "results_count": 0,
                "parent_id": None,
                "tool_name": tool_name,
                "args": args,
                "status": "started",
            }

        if any(
            x in tool_lower
            for x in ("scrape", "read", "fetch", "browse", "webpage", "url", "crawl", "visit")
        ):
            url = str(
                args.get("url")
                or args.get("webpage_url")
                or args.get("link")
                or args.get("uri")
                or ""
            )
            return {
                "id": evt_id,
                "type": "read",
                "url": url,
                "parent_id": last_search_id,
                "tool_name": tool_name,
                "args": args,
                "status": "started",
            }

        return {
            "id": evt_id,
            "type": "tool_call",
            "tool_name": tool_name,
            "args": args,
            "parent_id": last_search_id,
            "status": "started",
        }

    def _apply_result_to_event(self, evt: dict, result_str: str) -> None:
        """Enrich a trajectory event with tool result data (in-place)."""
        evt["result"] = self._truncate_event_payload(result_str)
        if self._is_error_result(result_str):
            evt["status"] = "error"
            evt["error"] = self._truncate_event_payload(result_str)
            return

        evt["status"] = "completed"
        if evt.get("type") == "search":
            results = self._parse_search_results(result_str)
            if results:
                evt["results"] = results
                evt["results_count"] = len(results)

    def _is_error_result(self, result_str: str) -> bool:
        """Best-effort error detection for tool result payloads."""
        if not result_str:
            return False
        try:
            parsed = json.loads(result_str)
            if isinstance(parsed, dict):
                if parsed.get("is_error") is True:
                    return True
                if isinstance(parsed.get("error"), (str, dict, list)):
                    return True
                if isinstance(parsed.get("errors"), list) and parsed["errors"]:
                    return True
        except Exception:
            pass

        lowered = result_str.lower()
        return (
            "tool execution failed" in lowered
            or "traceback" in lowered
            or "uncaught exception" in lowered
        )

    def _truncate_event_payload(self, text: str) -> str:
        """Truncate event payloads while preserving truncation visibility."""
        if len(text) <= _MAX_EVENT_RESULT_LENGTH:
            return text
        return text[:_MAX_EVENT_RESULT_LENGTH] + _TRUNCATION_SUFFIX

    def _parse_search_results(self, result_str: str) -> list[dict]:
        """Parse a JSON search-result string into a list of result dicts."""
        if not result_str:
            return []
        try:
            data = json.loads(result_str)
            organic: list | None = None
            if isinstance(data, dict):
                organic = (
                    data.get("organic")
                    or data.get("organic_results")
                    or data.get("results")
                )
            elif isinstance(data, list) and data and isinstance(data[0], dict):
                if data[0].get("link") or data[0].get("url"):
                    organic = data

            if organic and isinstance(organic, list):
                return [
                    {
                        "title": r.get("title"),
                        "url": r.get("link") or r.get("url") or "",
                        "snippet": r.get("snippet") or r.get("description"),
                        "favicon": r.get("favicon"),
                    }
                    for r in organic[:10]
                    if r.get("link") or r.get("url")
                ]
        except Exception:
            pass
        return []
