# SPDX-FileCopyrightText: 2025 MiromindAI
#
# SPDX-License-Identifier: Apache-2.0

"""
Fallback Final Answer Generator.

Ensures a visible, user-readable output is always produced in web_app contexts.
When no valid final answer exists after the regular output-processor chain, this
processor tries two strategies in order:

1. **B-style (preferred)**: asks the LLM to write a user-friendly final-answer
   summary based on the full conversation history.  The result is written to
   ``ctx.final_boxed_answer`` so that it flows into ``Task.final_answer`` in the
   web_app without any additional plumbing changes.

2. **A-style (last resort)**: if the B-style call fails (e.g. ContextLimitError
   or empty response), falls back to the structured failure-post-mortem style
   used by :class:`ExceedMaxTurnSummaryGenerator`.  The result is written to
   both ``ctx.final_boxed_answer`` and ``ctx.summary``.
"""
import re

from miroflow.agents.context import AgentContext
from miroflow.io_processor.base import BaseIOProcessor
from miroflow.io_processor.exceed_max_turn_summary_generator import (
    FAILURE_SUMMARY_ASSISTANT_PREFIX,
    ExceedMaxTurnSummaryGenerator,
)
from miroflow.llm.base import ContextLimitError
from miroflow.registry import ComponentType, register

from miroflow.logging.task_tracer import get_tracer #z
logger = get_tracer()
# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Placeholder / invalid-answer strings produced by FinalAnswerExtractor or the
# extract_gaia_final_answer helper when extraction failed or no real answer was
# found.  Any of these values means "no usable answer was produced".
# Keep in sync with eval_utils.INVALID_ANSWER_MARKERS.
_PLACEHOLDER_ANSWERS = frozenset(
    {
        "",
        "No final answer generated.",
        "Final response is generated by LLM, but no \\boxed{} content found.",
        # Returned by extract_gaia_final_answer when the summary contains no info
        "NO_ANSWER",
        "INSUFFICIENT_INFO",
        "CANNOT_DETERMINE",
        # Other common "no answer" markers from eval_utils.INVALID_ANSWER_MARKERS
        "None",
        "none",
        "N/A",
        "n/a",
        "NONE",
        "Unknown",
        "unknown",
        "UNKNOWN",
    }
)

# fmt: off
_FALLBACK_FINAL_THINK_CONTENT = (
    "Based on the full conversation history and the original task description, "
    "I need to write a comprehensive final answer for the user. "
    "I will summarise what was accomplished and provide the most helpful "
    "conclusion possible, **without calling any tools**."
)
# fmt: on

_FALLBACK_FINAL_ASSISTANT_PREFIX = (
    f"<think>\n{_FALLBACK_FINAL_THINK_CONTENT}\n</think>\n\n"
)

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _clean_llm_response(text: str) -> str:
    """Strip model artefacts and return clean Markdown text."""
    if not text:
        return ""
    # Remove all <think>…</think> blocks
    content = re.sub(r"<think>[\s\S]*?</think>", "", text).strip()
    # Remove tool-call blocks (should not appear, but guard anyway)
    content = re.sub(r"<use_mcp_tool>[\s\S]*", "", content).strip()
    # Remove empty \boxed{} patterns
    content = re.sub(r"\\boxed\{\s*\}", "", content).strip()
    return content


# ---------------------------------------------------------------------------
# Processor
# ---------------------------------------------------------------------------


@register(ComponentType.IO_PROCESSOR, "FallbackFinalAnswerGenerator")
class FallbackFinalAnswerGenerator(BaseIOProcessor):
    """Fallback output processor: guarantees at least one visible output.

    Execution order in ``agent_web_demo.yaml``:
      SummaryGenerator → FinalAnswerExtractor → ExceedMaxTurnSummaryGenerator
      → **FallbackFinalAnswerGenerator**  ← this class

    The processor is a no-op when a valid answer already exists.  Otherwise it
    tries B-style then A-style fallback (see module docstring).
    """

    USE_PROPAGATE_MODULE_CONFIGS = ("llm", "prompt")

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    async def run_internal(self, ctx: AgentContext) -> AgentContext:
        final_boxed = ctx.get("final_boxed_answer", "") or ""
        llm_extracted = ctx.get("llm_extracted_final_answer", "") or ""
        summary_val = ctx.get("summary", "") or ""
        history_len = len(ctx.get("message_history", []))
        logger.info(
            f'''FallbackFinalAnswerGenerator: final_boxed_answer={final_boxed[:80] if final_boxed else ""} | 
            llm_extracted_final_answer={llm_extracted[:80] if llm_extracted else ""} 
            | summary={summary_val[:80] if summary_val else ""} | message_history_len={history_len}"
            '''
        )

        if self._has_valid_answer(ctx):
            logger.info("FallbackFinalAnswerGenerator: valid answer already present — skipping fallback")
            return AgentContext()

        logger.info(
            f"FallbackFinalAnswerGenerator: no valid answer found (final_boxed={final_boxed[:80] if final_boxed else ''}) — running fallback"
        )

        task_description = ctx.get("task_description", "")
        message_history = self._prepare_message_history(ctx)

        # ── B-style: user-friendly final-answer summary ──────────────
        b_result = await self._try_b_style(message_history.copy(), task_description)
        if b_result:
            logger.info(
                f"FallbackFinalAnswerGenerator: B-style fallback succeeded, result={b_result[:120]}"
            )
            return AgentContext(
                final_boxed_answer=b_result,
                llm_extracted_final_answer=b_result,
            )
        logger.info("FallbackFinalAnswerGenerator: B-style fallback returned empty — trying A-style")
        # ── A-style: structured failure post-mortem ───────────────────
        a_result = await self._try_a_style(message_history.copy())
        if a_result:
            logger.info(
                f"FallbackFinalAnswerGenerator: A-style fallback succeeded, result={a_result[:120]}"
            )
            return AgentContext(
                final_boxed_answer=a_result,
                summary=a_result,
                exceed_max_turn_summary=a_result,
            )
        logger.warning("FallbackFinalAnswerGenerator: both B-style and A-style fallbacks failed — no output produced")
        return AgentContext()

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _has_valid_answer(ctx: AgentContext) -> bool:
        """Return True when a usable answer is already present in *ctx*.

        Only ``final_boxed_answer`` is checked because ``llm_extracted_final_answer``
        is the *full* LLM response text from FinalAnswerExtractor, which can be
        non-empty even when no real answer was found (e.g. the LLM explains why
        it cannot determine an answer).  Treating that as "valid" would cause the
        fallback to be silently skipped.
        """
        final_boxed = ctx.get("final_boxed_answer", "") or ""
        if final_boxed and final_boxed not in _PLACEHOLDER_ANSWERS:
            return True

        # llm_extracted = ctx.get("llm_extracted_final_answer", "") or ""
        # if llm_extracted and llm_extracted.strip():
        #     return True

        return False

    @staticmethod
    def _prepare_message_history(ctx: AgentContext) -> list:
        """Return a copy of message_history with a trailing user message removed."""
        history = ctx.get("message_history", []).copy()
        if history and history[-1].get("role") == "user":
            history.pop()
        return history

    async def _try_b_style(
        self, message_history: list, task_description: str
    ) -> str | None:
        """Call LLM with the *fallback_final_answer_prompt* and return clean text."""
        try:
            prompt = self.prompt_manager.render_prompt(
                "fallback_final_answer_prompt",
                context={"task_description": task_description},
            )
        except Exception:
            return None

        message_history.append(
            {"role": "user", "content": [{"type": "text", "text": prompt}]}
        )
        message_history.append(
            {"role": "assistant", "content": _FALLBACK_FINAL_ASSISTANT_PREFIX}
        )

        try:
            llm_response = await self.llm_client.create_message(
                message_history=message_history
            )
        except ContextLimitError:
            return None

        if llm_response.response_text:
            full = _FALLBACK_FINAL_ASSISTANT_PREFIX + llm_response.response_text
            return _clean_llm_response(full) or None

        return None

    async def _try_a_style(self, message_history: list) -> str | None:
        """Call LLM with the *exceed_max_turn_summary_prompt* and return clean text."""
        try:
            prompt = self.prompt_manager.render_prompt(
                "exceed_max_turn_summary_prompt", context={}
            )
        except Exception:
            return None

        message_history.append(
            {"role": "user", "content": [{"type": "text", "text": prompt}]}
        )
        message_history.append(
            {"role": "assistant", "content": FAILURE_SUMMARY_ASSISTANT_PREFIX}
        )

        try:
            llm_response = await self.llm_client.create_message(
                message_history=message_history
            )
        except ContextLimitError:
            return "Task could not be completed due to context limitations."

        if llm_response.response_text:
            full = FAILURE_SUMMARY_ASSISTANT_PREFIX + llm_response.response_text
            return (
                ExceedMaxTurnSummaryGenerator._extract_failure_experience_summary(full)
                or None
            )

        return None